# Generated by Django 5.2.17 on 2026-10-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MessageContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("traite", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
