# Generated by Django 5.2.17 on 2026-10-05 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Membre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut_carte",
                    models.CharField(
                        choices=[("active", "Active"), ("expiree", "Expirée")],
                        default="expiree",
                        max_length=10,
                    ),
                ),
                ("date_debut", models.DateField(blank=True, null=True)),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("profession", models.CharField(blank=True, max_length=150)),
                ("entreprise", models.CharField(blank=True, max_length=150)),
                ("ville", models.CharField(blank=True, max_length=100)),
                ("pays", models.CharField(blank=True, max_length=100)),
                ("bio", models.TextField(blank=True)),
                ("visible_annuaire", models.BooleanField(default=True)),
                (
                    "utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membre",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["utilisateur__nom"],
            },
        ),
    ]
