# Generated by Django 5.2.17 on 2026-10-05 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("reference_passerelle", models.CharField(blank=True, max_length=100)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=12)),
                ("devise", models.CharField(default="XOF", max_length=3)),
                (
                    "methode",
                    models.CharField(
                        choices=[
                            ("orange_money", "Orange Money"),
                            ("moov_money", "Moov Money"),
                            ("mtn_momo", "MTN Mobile Money"),
                            ("carte", "Carte bancaire"),
                        ],
                        max_length=20,
                    ),
                ),
                ("telephone", models.CharField(blank=True, max_length=30)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("initie", "Initié"),
                            ("confirme", "Confirmé"),
                            ("echoue", "Échoué"),
                        ],
                        default="initie",
                        max_length=10,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("date_confirmation", models.DateTimeField(blank=True, null=True)),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paiements",
                        to="members.membre",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
